# Generated by Django 5.2.16 on 2026-08-03 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('GMAIL', 'gmail'), ('QUICKBOOKS', 'quickbooks online')], default='GMAIL', max_length=20)),
                ('provider_message_id', models.CharField(max_length=200)),
                ('thread_id', models.CharField(blank=True, max_length=200)),
                ('history_id', models.CharField(blank=True, max_length=200)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('source_link', models.CharField(blank=True, max_length=1024)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='accounts.integrationconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'provider'], name='ingestion_s_company_53e674_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'provider_message_id'), name='uniq_sourcemsg_company_provider_extid')],
            },
        ),
    ]
