# Generated by Django 5.2.16 on 2026-08-03 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('qbo_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.accountingreference')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('raw_names', models.JSONField(blank=True, default=list)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('sender_domains', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('qbo_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.accountingreference')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('DISCOVERED', 'discovered'), ('FILE_PENDING', 'File pending'), ('CLASSIFICATION_PENDING', 'Classification pending'), ('EXTRACTION_PENDING', 'Extraction pending'), ('VALIDATION_PENDING', 'Validation pending'), ('MATCHING_PENDING', 'Matching pending'), ('POLICY_PENDING', 'Policy pending'), ('REVIEW_REQUIRED', 'Review required'), ('AUTO_POST_ELIGIBLE', 'Auto-post eligible'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('POSTING_PENDING', 'Posting pending'), ('POSTING_IN_PROGRESS', 'Posting in progress'), ('POSTED', 'Posted'), ('POSTING_FAILED', 'Posting failed'), ('POSTING_UNKNOWN', 'Posting outcome unknown')], default='DISCOVERED', max_length=30)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_breakdown', models.JSONField(blank=True, default=list)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('vendor_raw_name', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=128)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('payment_type', models.CharField(blank=True, choices=[('CREDIT_CARD', 'Credit card'), ('BANK', 'Bank / debit')], max_length=20)),
                ('memo', models.CharField(blank=True, max_length=512)),
                ('match_candidates', models.JSONField(blank=True, default=dict)),
                ('validations', models.JSONField(blank=True, default=list)),
                ('duplicate_candidates', models.JSONField(blank=True, default=list)),
                ('policy_decision', models.JSONField(blank=True, default=dict)),
                ('policy_outcome', models.CharField(blank=True, choices=[('REVIEW_REQUIRED', 'Review required'), ('AUTO_POST_ELIGIBLE', 'Auto-post eligible'), ('BLOCKED', 'Blocked'), ('REJECTED', 'Rejected')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.accountingreference')),
                ('interpretation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='documents.documentinterpretation')),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.accountingreference')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='documents.sourcedocument')),
                ('tax_code_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.accountingreference')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.project')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('VENDOR', 'Vendor'), ('PROJECT', 'Project'), ('CATEGORY', 'Expense category'), ('TAX', 'Tax code'), ('PAYMENT', 'Payment account')], max_length=20)),
                ('conditions', models.JSONField(default=dict)),
                ('outputs', models.JSONField(default=dict)),
                ('priority', models.IntegerField(default=100)),
                ('auto_post_permitted', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
            ],
            options={
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['company', 'scope', 'active'], name='expenses_ma_company_0f624a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_project_company_code'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_vendor_company_name'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'state'], name='expenses_ex_company_07f02b_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'policy_outcome'], name='expenses_ex_company_50d002_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'transaction_date'], name='expenses_ex_company_a04703_idx'),
        ),
    ]
