# Generated by Django 5.2.16 on 2026-08-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="line_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
