# Generated by Django 5.2.16 on 2026-08-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_line_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='match_candidates',
        ),
    ]
