# Generated by Django 5.2.16 on 2026-08-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_remove_expense_match_candidates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mappingrule",
            name="auto_post_permitted",
        ),
        migrations.AddField(
            model_name="expense",
            name="categorization",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="mappingrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mapping_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mappingrule",
            name="source_expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_rules",
                to="expenses.expense",
            ),
        ),
        migrations.AlterField(
            model_name="mappingrule",
            name="scope",
            field=models.CharField(
                choices=[
                    ("VENDOR", "Vendor"),
                    ("PROJECT", "Project"),
                    ("CATEGORY", "Expense category"),
                    ("LINE_CATEGORY", "Line item category"),
                    ("TAX", "Tax code"),
                    ("PAYMENT", "Payment account"),
                ],
                max_length=20,
            ),
        ),
    ]
