# Generated by Django 5.2.16 on 2026-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_remove_mappingrule_auto_post_permitted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="state",
            field=models.CharField(
                choices=[
                    ("DISCOVERED", "discovered"),
                    ("FILE_PENDING", "File pending"),
                    ("CLASSIFICATION_PENDING", "Classification pending"),
                    ("EXTRACTION_PENDING", "Extraction pending"),
                    ("VALIDATION_PENDING", "Validation pending"),
                    ("MATCHING_PENDING", "Matching pending"),
                    ("POLICY_PENDING", "Policy pending"),
                    ("REVIEW_REQUIRED", "Review required"),
                    ("AUTO_POST_ELIGIBLE", "Auto-post eligible"),
                    ("BLOCKED", "Blocked"),
                    ("REJECTED", "Rejected"),
                    ("APPROVED", "Approved"),
                    ("POSTING_PENDING", "Posting pending"),
                    ("POSTING_IN_PROGRESS", "Posting in progress"),
                    ("POSTED", "Posted"),
                    ("POSTING_FAILED", "Posting failed"),
                    ("POSTING_UNKNOWN", "Posting outcome unknown"),
                    ("AWAITING_BANK_MATCH", "Awaiting bank match"),
                    ("COMPLETED", "Completed"),
                ],
                default="DISCOVERED",
                max_length=30,
            ),
        ),
    ]
