# Generated by Django 5.2.16 on 2026-08-03 23:58

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='CAD', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive'), ('SUSPENDED', 'suspended')], default='ACTIVE', max_length=30)),
                ('timezone', models.CharField(default='America/vancouver', max_length=100)),
                ('auto_post_enabled', models.BooleanField(default=False)),
                ('tax_codes', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ACCOUNT', 'accountant')], max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.company')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('GMAIL', 'gmail'), ('QUICKBOOKS', 'quickbooks online')], max_length=30)),
                ('external_account_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CONNECTED', 'connected'), ('DISCONNECTED', 'disconnected'), ('EXPIRED', 'expired'), ('SYNC_FAILED', 'sync failed')], default='DISCONNECTED', max_length=30)),
                ('scopes', models.JSONField(default=list)),
                ('token_secret_ref', models.CharField(blank=True, max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, max_length=255)),
                ('sync_cursor_committed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'provider'), name='unique_connection_company_provider')],
            },
        ),
    ]
