# Generated by Django 5.2.16 on 2026-08-03 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(default="CAD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "active"),
                            ("INACTIVE", "inactive"),
                            ("SUSPENDED", "suspended"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("auto_post_enabled", models.BooleanField(default=False)),
                ("tax_codes", models.JSONField(default=list)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
    ]
