# Generated by Django 5.2.16 on 2026-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integrationconnection",
            name="token_secret_ref",
        ),
        migrations.AddField(
            model_name="integrationconnection",
            name="encrypted_secret_ref",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="tax_codes",
            field=models.JSONField(default=list, null=True),
        ),
    ]
