# Generated by Django 5.2.16 on 2026-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_integrationconnection_token_secret_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tax_codes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
