# Generated by Django 5.2.16 on 2026-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_company_tax_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='last_error',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
