# Generated by Django 5.2.16 on 2026-08-03 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ATTACHMENT', 'Attachment'), ('EMAIL_BODY', 'Email body')], default='ATTACHMENT', max_length=20)),
                ('provider_attachment_id', models.CharField(blank=True, max_length=255)),
                ('object_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('FAILED', 'Scan failed')], default='PENDING', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ingestion.sourcemessage')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentInterpretation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('PAID_INVOICE', 'Paid invoice'), ('UNPAID_INVOICE', 'Unpaid invoice'), ('REFUND_CREDIT', 'Refund / credit'), ('PURCHASE_ORDER', 'Purchase order'), ('STATEMENT', 'Statement'), ('IRRELEVANT', 'Irrelevant'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('classification_method', models.CharField(choices=[('RULE', 'Rule'), ('AI', 'AI'), ('MANUAL', 'Manual')], max_length=10)),
                ('classification_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('extraction_method', models.CharField(blank=True, choices=[('EMBEDDED_TEXT', 'Embedded PDF text'), ('TEMPLATE', 'Known template'), ('OCR', 'OCR'), ('VISION_AI', 'Vision AI'), ('MANUAL', 'Manual entry')], max_length=20)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('ABSTAINED', 'Abstained'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('schema_version', models.CharField(blank=True, max_length=32)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('model_identifier', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('raw_response_ref', models.CharField(blank=True, max_length=512)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interpretations', to='documents.sourcedocument')),
            ],
            options={
                'ordering': ['document', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['company', 'sha256'], name='documents_s_company_269bf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('message', 'provider_attachment_id'), name='uniq_document_message_attachment'),
        ),
        migrations.AddConstraint(
            model_name='documentinterpretation',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uniq_interpretation_document_version'),
        ),
    ]
