"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import secrets
import os
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY',default='super-secret-key')
TOKEN_ENCRYPTION_KEY= config("TOKEN_ENCRYPTION_KEY")

GOOGLE_CLIENT_ID=  config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")
GOOGLE_REDIRECT_URI = config("GOOGLE_REDIRECT_URI",
                             default="http://localhost:8000/api/v1/integrations/gmail/callback")
GOOGLE_OAUTH_SCOPES = config("GOOGLE_OAUTH_SCOPES",
                             default="https://www.googleapis.com/auth/gmail.readonly")

# Intuit / QuickBooks Online OAuth (sandbox)
INTUIT_CLIENT_ID = config("INTUIT_CLIENT_ID", default="")
INTUIT_CLIENT_SECRET = config("INTUIT_CLIENT_SECRET", default="")
INTUIT_REDIRECT_URI = config("INTUIT_REDIRECT_URI",
                             default="http://localhost:8000/api/v1/integrations/quickbooks/callback")
INTUIT_SCOPES = config("INTUIT_SCOPES", default="com.intuit.quickbooks.accounting")
INTUIT_ENVIRONMENT = config("INTUIT_ENVIRONMENT", default="sandbox")
QBO_API_BASE = ("https://sandbox-quickbooks.api.intuit.com"
                if INTUIT_ENVIRONMENT == "sandbox"
                else "https://quickbooks.api.intuit.com")
QBO_MINOR_VERSION = config("QBO_MINOR_VERSION", default="73")
INTUIT_AUTH_URL = config(
      "INTUIT_AUTH_URL",
      default="https://appcenter.intuit.com/connect/oauth2",
  )

INTUIT_TOKEN_URL = config(
      "INTUIT_TOKEN_URL",
      default="https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
  )

INTUIT_REVOKE_URL = config(
      "INTUIT_REVOKE_URL",
      default="https://developer.api.intuit.com/v2/oauth2/tokens/revoke",
  )

QBO_API_BASE = config(
      "QBO_API_BASE",
      default=(
          "https://sandbox-quickbooks.api.intuit.com"
          if INTUIT_ENVIRONMENT == "sandbox"
          else "https://quickbooks.api.intuit.com"
      ),
  )



# Celery: Redis broker, NO result backend (Dev Guide 3.c). REMOVE the existing
# CELERY_RESULT_BACKEND line and replace the celery block with:
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = None
CELERY_TASK_DEFAULT_QUEUE = "default"

OBJECT_STORAGE_ROOT = config("OBJECT_STORAGE_ROOT",
                             default=str(BASE_DIR / "var" / "objects"))
MAX_UPLOAD_BYTES = 15 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

MALWARE_SCAN_ENABLED = config("MALWARE_SCAN_ENABLED", default=False, cast=bool)
MONEY_ROUNDING_TOLERANCE = Decimal("0.02")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'ingestion',
    'documents',
    'expenses',
    'operations',
    'accounting',
    'common',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework.authentication.SessionAuthentication',

    ),
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER':'common.api.api_exception_handler',
}



CACHES = {
    'default':{
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':config('REDIS_URL'),
        'OPTIONS':{
            'CLIENT_CLASS':'django_redis.client.DefaultClient',
        }
    }
}

REDIS_URL = config('REDIS_URL')
SECRET_SALT = config('SECRET_KEY') or secrets.token_hex(16)

CELERY_BROKER_URL = config('CELERY_BROKER_URL',default='redis://localhost:6379')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND',default='redis://localhost:6379')
CELERY_BEAT_SCHEDULE = 'django_celery_beat.schedulers:DatabaseScheduler'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGGING_DIR = os.path.join(BASE_DIR, 'config', 'logs')
if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)
LOGGING ={
    'version':1,
    'disable_existing_loggers':False,
    'formatters':{
        'verbose':{
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple':{
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers':{
        'console':{
            'class':'logging.StreamHandler',
            'formatter':'simple',
        },
    },
    'loggers':{
        'django':{
            'handlers':['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL','INFO'),
        },
    },
}



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
