# Generated by Django 5.2.16 on 2026-08-03 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('DISCOVERY', 'Discovery'), ('DOWNLOAD', 'Download'), ('FILE_CHECK', 'File check'), ('CLASSIFICATION', 'Classification'), ('EXTRACTION', 'Extraction'), ('MATCH', 'Match'), ('RULE_APPLIED', 'Rule applied'), ('AI_CALL', 'AI call'), ('CORRECTION', 'Field correction'), ('APPROVAL', 'Approval'), ('REJECTION', 'Rejection'), ('DUPLICATE_RESOLUTION', 'Duplicate resolution'), ('POLICY_DECISION', 'Policy decision'), ('POSTING_ATTEMPT', 'Posting attempt'), ('POSTING_RESULT', 'Posting result'), ('EXCEPTION', 'Exception'), ('RETRY', 'Retry')], max_length=30)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'System'), ('USER', 'User'), ('AI', 'AI'), ('PROVIDER', 'External provider')], default='SYSTEM', max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('object_version', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'aggregate_type', 'aggregate_id'], name='operations__company_f3da91_idx'), models.Index(fields=['company', 'event_type'], name='operations__company_4e3329_idx'), models.Index(fields=['correlation_id'], name='operations__correla_01f582_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExceptionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('stage', models.CharField(blank=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('retryable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='OPEN', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('aggregate_type', models.CharField(blank=True, max_length=64)),
                ('aggregate_id', models.CharField(blank=True, max_length=64)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='expenses.expense')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status', 'severity'], name='operations__company_31f74f_idx'), models.Index(fields=['company', 'code'], name='operations__company_a1a89f_idx')],
            },
        ),
    ]
