# Generated by Django 5.2.16 on 2026-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DISCOVERY", "Discovery"),
                    ("DOWNLOAD", "Download"),
                    ("FILE_CHECK", "File check"),
                    ("CLASSIFICATION", "Classification"),
                    ("EXTRACTION", "Extraction"),
                    ("MATCH", "Match"),
                    ("RULE_APPLIED", "Rule applied"),
                    ("AI_CALL", "AI call"),
                    ("CORRECTION", "Field correction"),
                    ("APPROVAL", "Approval"),
                    ("REJECTION", "Rejection"),
                    ("DUPLICATE_RESOLUTION", "Duplicate resolution"),
                    ("POLICY_DECISION", "Policy decision"),
                    ("POSTING_ATTEMPT", "Posting attempt"),
                    ("POSTING_RESULT", "Posting result"),
                    ("EXCEPTION", "Exception"),
                    ("RETRY", "Retry"),
                    ("CONFIG_UPDATED", "Company config updated"),
                    ("INTEGRATION_CONNECTED", "Integration connected"),
                    ("INTEGRATION_REVOKED", "Integration revoked"),
                    ("REFERENCE_SYNCED", "Reference data synced"),
                    ("PROJECT_CREATED", "Project created"),
                    ("PROJECT_UPDATED", "Project updated"),
                    ("PROJECT_CLOSED", "Project closed"),
                    ("PROJECT_LINKED", "Project linked to QBO customer"),
                    ("VALIDATION", "Validation run"),
                    ("STATE_CHANGED", "Expense state changed"),
                    ("CATEGORIZATION", "Categorization"),
                    ("BANK_MATCH_CONFIRMED", "Bank match confirmed"),
                ],
                max_length=30,
            ),
        ),
    ]
