# Generated by Django 5.2.16 on 2026-08-03 23:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('ACCOUNT', 'Account'), ('CUSTOMER', 'Customer / project'), ('TAX_CODE', 'Tax code'), ('PAYMENT_ACCOUNT', 'Payment account')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sync_token', models.CharField(blank=True, max_length=255)),
                ('qbo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PostingIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_version', models.PositiveIntegerField()),
                ('transaction_purpose', models.CharField(choices=[('PURCHASE', 'Purchase')], default='PURCHASE', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('request_id', models.UUIDField()),
                ('doc_number_token', models.CharField(max_length=32)),
                ('minor_version', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('IN_PROGRESS', 'In progress'), ('POSTED', 'Posted'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown outcome')], default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=64)),
                ('qbo_entity_type', models.CharField(blank=True, max_length=32)),
                ('qbo_entity_id', models.CharField(blank=True, max_length=64)),
                ('qbo_sync_token', models.CharField(blank=True, max_length=32)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('response_summary', models.JSONField(blank=True, default=dict)),
                ('last_error', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
