# Generated by Django 5.2.16 on 2026-08-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('accounts', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingreference',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='accountingreference',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references', to='accounts.integrationconnection'),
        ),
        migrations.AddField(
            model_name='postingintent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)s', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='postingintent',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_intents', to='expenses.expense'),
        ),
        migrations.AddIndex(
            model_name='accountingreference',
            index=models.Index(fields=['company', 'entity_type', 'active'], name='accounting__company_e9be18_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingreference',
            constraint=models.UniqueConstraint(fields=('company', 'entity_type', 'external_id'), name='uniq_accref_company_type_extid'),
        ),
        migrations.AddConstraint(
            model_name='postingintent',
            constraint=models.UniqueConstraint(fields=('expense', 'expense_version', 'transaction_purpose'), name='uniq_intent_expense_version_purpose'),
        ),
        migrations.AddConstraint(
            model_name='postingintent',
            constraint=models.UniqueConstraint(condition=models.Q(('qbo_entity_id__gt', '')), fields=('company', 'qbo_entity_id'), name='uniq_intent_company_qbo_entity'),
        ),
    ]
