# Generated by Django 5.2.16 on 2026-08-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingreference',
            name='entity_type',
            field=models.CharField(choices=[('COMPANY_INFO', 'Company info'), ('VENDOR', 'Vendor'), ('ACCOUNT', 'Account'), ('CUSTOMER', 'Customer / project'), ('ITEM', 'Item'), ('TAX_CODE', 'Tax code'), ('PAYMENT_ACCOUNT', 'Payment account')], max_length=30),
        ),
    ]
