# Generated by Django 5.2.16 on 2026-08-13 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_alter_accountingreference_entity_type"),
        ("accounts", "0004_integrationconnection_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickBooksPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qbo_purchase_id", models.CharField(max_length=64)),
                ("qbo_sync_token", models.CharField(blank=True, max_length=32)),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="CAD", max_length=3)),
                ("vendor_ref_id", models.CharField(blank=True, max_length=64)),
                ("vendor_ref_name", models.CharField(blank=True, max_length=255)),
                ("vendor_ref_type", models.CharField(blank=True, max_length=20)),
                ("payment_account_ref_id", models.CharField(blank=True, max_length=64)),
                (
                    "payment_account_ref_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("payment_type", models.CharField(blank=True, max_length=20)),
                ("doc_number", models.CharField(blank=True, max_length=64)),
                ("memo", models.CharField(blank=True, max_length=512)),
                (
                    "total_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_credit", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("VOIDED", "Voided"),
                            ("DELETED", "Deleted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("qbo_last_updated_at", models.DateTimeField(blank=True, null=True)),
                ("local_last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("has_attachment", models.BooleanField(default=False)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="accounts.company",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="accounts.integrationconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuickBooksPurchaseLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField(default=0)),
                ("qbo_line_id", models.CharField(blank=True, max_length=32)),
                ("detail_type", models.CharField(blank=True, max_length=48)),
                ("description", models.CharField(blank=True, max_length=512)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("expense_account_ref_id", models.CharField(blank=True, max_length=64)),
                (
                    "expense_account_ref_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("customer_ref_id", models.CharField(blank=True, max_length=64)),
                ("customer_ref_name", models.CharField(blank=True, max_length=255)),
                ("class_ref_id", models.CharField(blank=True, max_length=64)),
                ("class_ref_name", models.CharField(blank=True, max_length=255)),
                ("tax_code_ref_id", models.CharField(blank=True, max_length=64)),
                ("item_ref_id", models.CharField(blank=True, max_length=64)),
                ("item_ref_name", models.CharField(blank=True, max_length=255)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="accounts.company",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.quickbookspurchase",
                    ),
                ),
            ],
            options={
                "ordering": ["purchase", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="QuickBooksSyncState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("REFERENCE", "Reference data"),
                            ("PURCHASE", "Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_successful_cursor", models.DateTimeField(blank=True, null=True)),
                (
                    "last_webhook_received_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_cdc_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_cdc_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Idle"),
                            ("RUNNING", "Running"),
                            ("HEALTHY", "Healthy"),
                            ("FAILED", "Failed"),
                        ],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
                ("last_error", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="accounts.company",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_states",
                        to="accounts.integrationconnection",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="quickbookspurchase",
            index=models.Index(
                fields=["company", "transaction_date"],
                name="accounting__company_0b5163_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quickbookspurchase",
            index=models.Index(
                fields=["company", "total_amount"],
                name="accounting__company_a0688b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quickbookspurchase",
            index=models.Index(
                fields=["company", "status"], name="accounting__company_868f89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quickbookspurchase",
            index=models.Index(
                fields=["company", "vendor_ref_id"],
                name="accounting__company_08c901_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="quickbookspurchase",
            constraint=models.UniqueConstraint(
                fields=("company", "qbo_purchase_id"),
                name="uniq_qbopurchase_company_extid",
            ),
        ),
        migrations.AddIndex(
            model_name="quickbookspurchaseline",
            index=models.Index(
                fields=["purchase", "line_number"],
                name="accounting__purchas_33ac2c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="quickbookssyncstate",
            constraint=models.UniqueConstraint(
                fields=("company", "entity_type"),
                name="uniq_qbosyncstate_company_entity",
            ),
        ),
    ]
