# Generated by Django 5.2.16 on 2026-08-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_quickbookspurchase_quickbookspurchaseline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quickbookspurchaseline",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="quickbookspurchaseline",
            name="company",
        ),
        migrations.RemoveField(
            model_name="quickbookssyncstate",
            name="company",
        ),
        migrations.RemoveField(
            model_name="quickbookssyncstate",
            name="connection",
        ),
        migrations.DeleteModel(
            name="QuickBooksPurchase",
        ),
        migrations.DeleteModel(
            name="QuickBooksPurchaseLine",
        ),
        migrations.DeleteModel(
            name="QuickBooksSyncState",
        ),
    ]
