# Generated by Django 5.2.16 on 2026-08-18 16:58

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_remove_quickbookspurchaseline_purchase_and_more"),
        ("accounts", "0004_integrationconnection_last_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        related_query_name="%(app_label)s_%(class)s",
                        to="accounts.company",
                    ),
                ),
                (
                    "reference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_row",
                        to="accounting.accountingreference",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company"], name="accounting__company_00f00d_idx"
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="refembedding_hnsw_cosine",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
