# Generated by Django 5.2.16 on 2026-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_referenceembedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="postingintent",
            name="approved_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="postingintent",
            name="bank_matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
